name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Ensure no Windows line endings
      run: ./validate.sh
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test (Hedgehog.Tests)
      run: dotnet test --no-build --configuration Release --verbosity normal tests/Hedgehog.Tests/Hedgehog.Tests.fsproj
    - name: Test (Hedgehog.Linq.Tests)
      run: dotnet test --no-build --configuration Release --verbosity normal tests/Hedgehog.Linq.Tests/Hedgehog.Linq.Tests.csproj

  fable-tests:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJs
      uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
    - name: Install npm packages
      run: npm install
      working-directory: ./tests/Hedgehog.Tests
    - name: Fable Tests (Hedgehog.Tests)
      run: |
        dotnet tool restore
        npm test
      working-directory: ./tests/Hedgehog.Tests
